QUEEN = 'Q'
ANT = 'A'
SPIDER = 'S'
COCKROACH = 'C'
GRASSHOPPER = 'G'
NO_PIECE = 'N'
ALL_PIECES = (QUEEN, ANT, COCKROACH, GRASSHOPPER, SPIDER)

PLACED = 'Placed'

ONGOING = 0
PLAYER1_WIN = 1
PLAYER2_WIN = 2
DRAW = 3

POP = 'P'
NEW = 'N'
PASS = 'pass'

PVP = 'pvp'
AI_AS_FIRST_PLAYER = 'ai1'
AI_AS_SECOND_PLAYER = 'ai2'

PASS_ACTION = (PASS, None, None)

DEFAULT_COEFFICIENTS = (1, 2, 3, 1, 4, 2, 8)
